<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/17 10:31:33
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_notices_on_homepage' => 10,
  'app_max_notices_on_category' => 20,
));
