<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/08/05 04:09:44
sfConfig::add(array(
  'mod_sfcooperationlanguage_enabled' => true,
  'mod_sfcooperationlanguage_view_class' => 'sfPHP',
));
