<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/08/05 04:10:08
sfConfig::add(array(
  'mod_sfcooperationarticle_enabled' => true,
  'mod_sfcooperationarticle_view_class' => 'sfPHP',
));
