# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing
# apps/frontend/config/routing.yml
#notice:
#  class:   sfDoctrineRouteCollection
#  options: { model: CooperationNotice }

# default rules
localized_homepage:
  url:   /:sf_culture/
  param: { module: notice, action: index }
  requirements:
    sf_culture: (?:fr|en)

homepage:
  url:   /
  param: { module: notice, action: index }

change_language:
  url:   /change_language
  param: { module: language, action: changeLanguage }

affiliate:
  class:   sfDoctrineRouteCollection
  options:
    model: CooperationAffiliate
    actions:        [new, create]
    object_actions: { wait: get }
    prefix_path:    /:sf_culture/affiliate

category:
  url:     /:sf_culture/category/:slug.:sf_format
  class:   sfDoctrineRoute
  param:   { module: category, action: show, sf_format: html }
  options: { model: CooperationCategory, type: object, method: doSelectForSlug }
  requirements:
    sf_format: (?:html|atom)

notice_search:
  url:   /:sf_culture/search.:sf_format
  param: { module: notice, action: search, sf_format: html }
  requirements:
    sf_format: (?:html|js)

notice:
  class: sfDoctrineRouteCollection
  options:
    model:          CooperationNotice
    column:         token
    object_actions: { publish: put, extend: put }
    prefix_path:    /:sf_culture/notice
  requirements:
    token: \w+

notice_show_user:
  url:     /:sf_culture/notice/:company_slug/:location_slug/:id/:position_slug
  class:   sfDoctrineRoute
  options:
    model: CooperationNotice
    type:  object
    method_for_query: retrieveActiveNotice
  param:   { module: notice, action: show }
  requirements:
    id: \d+
    sf_method: [GET]

###########################################################################

notice_new:
  url:     /notice/new.:sf_format
  class:   sfDoctrineRoute
  options: { model: CooperationNotice, type: object }
  param:   { module: notice, action: new, sf_format: html }
  requirements: { sf_method: get }

notice_create:
  url:     /notice.:sf_format
  class:   sfDoctrineRoute
  options: { model: CooperationNotice, type: object }
  param:   { module: notice, action: create, sf_format: html }
  requirements: { sf_method: post }

notice_edit:
  url:     /notice/:id/edit.:sf_format
  class:   sfDoctrineRoute
  options: { model: CooperationNotice, type: object }
  param:   { module: notice, action: edit, sf_format: html }
  requirements: { sf_method: get }

notice_update:
  url:     /notice/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: CooperationNotice, type: object }
  param:   { module: notice, action: update, sf_format: html }
  requirements: { sf_method: put }

notice_delete:
  url:     /notice/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: CooperationNotice, type: object }
  param:   { module: notice, action: delete, sf_format: html }
  requirements: { sf_method: delete }

notice_show:
  url:     /notice/:id.:sf_format
  class:   sfDoctrineRoute
  options: { model: CooperationNotice, type: object }
  param:   { module: notice, action: show, sf_format: html }
  requirements: { sf_method: get }

api_notices:
  url:     /api/:token/notices.:sf_format
  class:   sfDoctrineRoute
  param:   { module: api, action: list }
  options: { model: CooperationNotice, type: list, method: getForToken }
  requirements:
    sf_format: (?:xml|json|yaml)

