<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/08/05 04:10:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=cooperation',
  'username' => 'root',
  'password' => '564d886a9e99',
  'name' => 'doctrine',
)),);
