<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/08/05 04:10:50
sfConfig::add(array(
  'mod_sfcooperationmobile_enabled' => true,
  'mod_sfcooperationmobile_view_class' => 'sfPHP',
));
