<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/08/05 09:50:01
sfConfig::add(array(
  'mod_sfcooperationcategory_enabled' => true,
  'mod_sfcooperationcategory_view_class' => 'sfPHP',
));
