<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/17 22:19:43
sfConfig::add(array(
  'mod_sfcooperationmobile_enabled' => true,
  'mod_sfcooperationmobile_view_class' => 'sfPHP',
));
