dev:
  doctrine:
    class: sfDoctrineDatabase
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=cooperation'
      username: root
      password: '123456'
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=cooperation_test'
      username: root
      password: '123456'
