dev:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=cooperation'
      username: root
      password: '564d886a9e99'
prod:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=cooperation'
      username: root
      password: '564d886a9e99'
test:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=cooperation_test'
      username: root
      password: '564d886a9e99'
