<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/04 12:38:55
sfConfig::add(array(
  'mod_sfcooperationnotice_enabled' => true,
  'mod_sfcooperationnotice_view_class' => 'sfPHP',
));
