<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/17 16:01:36
sfConfig::add(array(
  'mod_sfcooperationmain_enabled' => true,
  'mod_sfcooperationmain_view_class' => 'sfPHP',
));
