<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/17 22:19:37
sfConfig::add(array(
  'mod_sfcooperationlanguage_enabled' => true,
  'mod_sfcooperationlanguage_view_class' => 'sfPHP',
));
