<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/15 13:43:08
sfConfig::add(array(
  'mod_sfcooperationmain_enabled' => true,
  'mod_sfcooperationmain_view_class' => 'sfPHP',
));
