<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/13 23:00:13
sfConfig::add(array(
  'mod_sfcooperationlanguage_enabled' => true,
  'mod_sfcooperationlanguage_view_class' => 'sfPHP',
));
