<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/13 23:00:31
sfConfig::add(array(
  'mod_sfcooperationnotice_enabled' => true,
  'mod_sfcooperationnotice_view_class' => 'sfPHP',
));
