<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/13 23:27:15
sfConfig::add(array(
  'mod_sfcooperationcategory_enabled' => true,
  'mod_sfcooperationcategory_view_class' => 'sfPHP',
));
